### PR TITLE
Removed dependency on IServiceProvider from endpoint and action filter constructors.

### PR DESCRIPTION
**Pull request by mgernand**
The service provider is available via the HTTP context.

### CODE REVIEW

**Comment by mvdgun** [comment]
Hi @mgernand, I just merge a couple of pull requests and unfortunately your pull request has conflicts now :(. From the looks of it it's shouldn't be very hard to resolve.

**Comment by mgernand** [comment]
No problem. I'll take a look tomorrow. 🙂

**Comment by mvdgun** [comment]
Great! Could you also remove `this.` when accessing class members? The whole code bases doesn't use it and I want to keep things consistent.

**Comment by mgernand** [comment]
@mvdgun The tests of the current release/1.4 branch has errors. So I will wait until those are fixed and will open another PR then.

**Comment by mvdgun** [comment]
@mgernand I just fixed the tests in the release/1.4 branch

**Comment by mgernand** [comment]
@mvdgun I just opened PR #30 with the changes from this PR (and without this prefixed).

**Pull request closed without merging**
